### ISSUE TITLE
Build issue on Ubuntu 20.04

### ISSUE THREAD

**Issue by dhanajik** [Leuconoe/MediaPipeUnityPluginLinuxInstaller#1]
Hi

Thank you for your great work.

I am trying to use Mediapipe with Unity for the Android platform. I have built a MediapipeUnityPlugin repository on Ubuntu for the android platform and import it to the Unity editor and built the APK and installed it successfully on my android phone. But it is not working or not streaming the camera.

I want to make changes in MediapipeUnityPlugin as per my requirement and build the apk for the android phone.

Please provide your guidance 

THank you
D

**Comment by Leuconoe** [comment]
Have you created aar library for android?, can you check the error in logcat?
If the library was created, this script did work.
You need to inquire at MediapipeUnityPlugin.

**Comment by Leuconoe** [comment]
@dhanajik Has the problem been solved? Or do you have additional questions?
